version: "3.9"
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    command: rails server -b 0.0.0.0
    volumes:
      - ./backend:/var/app

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

volumes:
  postgres_data: